---
- name: Installing Open Edx Hawthorn Release
  hosts: all


  tasks:
  - name: Updates apt cache
    action: apt update_cache=true
    become: true

  - name: upgrade all packages
    apt:
      name: "*"
      force_apt_get: True
      state: latest

  - name: Cloning git repository
    git:
      repo: 'https://github.com/mohammadahsan/edx-ansible.git'
      dest: /etc/edxInstall

  - name: Installing Ansible bootstrap
    shell: sh /etc/edxInstall/ansible-bootstrap.sh >> ansible-bootstrap.txt

  - name: Generating Passwords
    shell: sh /etc/edxInstall/generate-passwords.sh >> generate-passwords.txt

  - name: Installing EDX Hawthorn Release
    shell: sh /etc/edxInstall/native.sh >> native.txt
